name: test_proj_android_setup
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  provider: ^6.0.0
  bloc_concurrency: ^0.2.0
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.2.11
  sizer: ^2.0.15


flutter_icons:
  image_path: 'assets/launcher/logo_launcher.png'
  adaptive_icon_background: '#343434'
  adaptive_icon_foreground: 'assets/launcher/logo_launcher_adaptative.png'
  android: 'ic_launcher'
  ios: true
  remove_alpha_ios: true

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  effective_dart: ^1.0.0
  flutter_lints: ^2.0.1



flutter_native_splash:
  image: assets/images/logo.png



flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic

